name: felvera
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Dart SDK sürümü uyumluluğu

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.14
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.6
  # Diğer bağımlılıklar
  google_ml_kit: ^0.19.0
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  flutter_svg: ^2.0.9
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  mailer: ^6.1.2
  uuid: ^3.0.0
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.15
  flutter_email_sender: ^5.0.2
  flutter_localizations:
    sdk: flutter
  url_strategy: ^0.3.0
  flutter_native_splash: ^2.4.2
  flutter_web_plugins:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/resim.png
    - assets/proarka.jpg
    - assets/images/logo_felveraa.png
